-- Autogenerated by migration tool on 2022-05-21 23:16:18
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: datadog_monitors
CREATE TABLE IF NOT EXISTS "datadog_monitors" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"meta_id" text,
	"id" integer,
	"name" text,
	"type" text,
	"created" timestamp without time zone,
	"deleted" timestamp without time zone,
	"modified" timestamp without time zone,
	"creator_email" text,
	"creator_handle" text,
	"creator_name" text,
	"message" text,
	"multi" boolean,
	"options" jsonb,
	"overall_state" text,
	"state" jsonb,
	"priority" text,
	"query" text,
	"restricted_roles" text[],
	"tags" text[],
	CONSTRAINT datadog_monitors_pk PRIMARY KEY(cq_fetch_date,meta_id),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('datadog_monitors');
